language: go

go:
  - 1.13.x

services:
  - docker

before_install:
  # Get latest docker version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Enable experimental for buildx tool
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json

install:
  # Get Nigiri-travis for testing
  - mkdir -p tmp; cd tmp
  - curl https://travis.nigiri.network | bash; cd ..
  - docker-compose -f tmp/docker-compose.yml up -d

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted"; exit 1; fi
  - bash scripts/test ci
  - bash scripts/build linux amd64
  - docker-compose -f tmp/docker-compose.yml down
  - sudo rm -rf tmp

before_deploy:
  # Create a builder
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use

deploy:
  provider: script
  script: bash scripts/deploy
  on:
    all_branches: true
